In [1]:
file = open(r"500input.txt", "r")

In [2]:
file

<_io.TextIOWrapper name='500input.txt' mode='r' encoding='cp950'>

In [3]:
data = file.readlines()

In [4]:
file.close()

In [5]:
from numpy import *

In [6]:
dim = int(sqrt(len(data)/2))

In [7]:
m1 = zeros((dim, dim))
m2 = zeros((dim, dim))

In [8]:
for i in range(len(data)):
    data[i] = data[i].strip()
    data[i] = data[i].split(',')

In [9]:
sign = data[0][0]

In [10]:
len(data)

500000

In [11]:
for i in range(len(data)):
    if data[i][0] == sign:
        index1 = int(data[i][1])
        index2 = int(data[i][2])
        m1[index1, index2] = float(data[i][3])
    else :
        index1 = int(data[i][1])
        index2 = int(data[i][2])
        m2[index1, index2] = float(data[i][3])

In [12]:
m1

array([[51., 17., 83., ..., 23., 47., 52.],
       [38., 63., 43., ..., 65., 18., 48.],
       [78., 80., 45., ..., 44., 56., 61.],
       ...,
       [19., 18., 16., ..., 96., 50., 26.],
       [20., 60., 12., ..., 95., 88., 61.],
       [39., 43., 91., ..., 36., 76., 16.]])

In [13]:
m2

array([[73., 58., 23., ..., 81., 46.,  8.],
       [36., 44.,  0., ..., 63., 47., 11.],
       [ 9., 41.,  1., ..., 24., 92., 47.],
       ...,
       [60., 77.,  7., ..., 32.,  1., 28.],
       [91., 91., 32., ..., 86., 65., 70.],
       [48., 38., 47., ..., 42., 93., 53.]])

In [14]:
output = dot(m1, m2)

In [15]:
output

array([[1224217., 1209205., 1172528., ..., 1220560., 1194145., 1139598.],
       [1193505., 1207761., 1167187., ..., 1236379., 1193668., 1139242.],
       [1268862., 1215681., 1187852., ..., 1228948., 1236998., 1169572.],
       ...,
       [1283557., 1278193., 1252259., ..., 1261329., 1250857., 1215844.],
       [1285557., 1267572., 1220170., ..., 1263092., 1208709., 1201931.],
       [1246537., 1191511., 1173756., ..., 1198548., 1189622., 1172100.]])

In [16]:
file = open("mapreduce_output.txt", "w")

In [17]:
file.write("Output\n")

7

In [18]:
for i in range(len(output)):
    for j in range(len(output[i])):
        file.write(str(i))
        file.write(", ")
        file.write(str(j))
        file.write(", ")
        file.write(str(int(output[i][j])))
        file.write(' \n')